# Exercise 12-06 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app02-pod
  namespace: default
  labels:
    bu: dev
    env: dev
    tier: mid
spec:
  containers:
  - name: busy-app
    image: busybox
    command:
    - sleep
    - "4800"
