# Exercise 12-06 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: db02-pod
  namespace: default
  labels:
    bu: fin
    env: test
    tier: db
spec:
  containers:
  - name: db-app
    image: redis
