# Exercise: 29-02 v3.2.0
#
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ingress-nginx-admission
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2R6Q0NBVjhDQVFBd01qRWdNQjRHQTFVRUF3d1hhVzVuY21WemN5MXVaMmx1ZUMxaFpHMXBjM05wYjI0eApEakFNQmdOVkJBb01CVzVuYVc1NE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnhTOFVrVzc5cStRYVRTcHRVSUdJRUNpblkrVUoxbERFWFMrL0M1VGNXSTBnQUJOcUFrWStDOU5Ic3ZWMDRBZTAKc1FPd1lwb0xZNjlDTk1PbmFoVVkrUnpmakFRc050QWZ0L1MwRTVGa2FkTVNuam54Q3FpR3VUTjlJY0tBK2FodQpTeTBrQ2p1MmlvTGNlTFpTbVcyKzBCb3ZDTWtjblh0cEVDRk5wQnhneVlRZ3lYdXZKTU5wRWJZbE5HWllmVmhoCjdBL0dOUGdpZTZLQ0ZHY1F1YzRISjhkV0RVNXpZYmM3dGZ3QUUrSFJmNlBRMDlIQXN3anptNEFWNVJ0bXdtYlYKWnQxYWhpSXRqZG1rd1A2dHA4cW9UNUh2bTJGTGF0WVBydUhNUHkzaC94czc3bGlYWXBTN2E1ek5NaERweTZCWQo1aVBYejlMWFBDTC9POHNnUlAweUZRSURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLTFRMSkpMCkFVSmNUbkVzS1JWajM2akZnZ0RrSVJSdGNWTlJ4TVlqRUdLbVk3VUF5K0NhWG5LOUttVDV4SFl0SHVTUTROQSsKQU9WZ3RXOHJLYWpLSGxTTWVZL3RuNC9OVUx2TlU5R2VWYjM5RldQUmthenZVSVNqY1ZNNHhINWd1ZFljbzJsSAp2NFNEaFpQckpnUVpkZU4xd1F1eDBCdndPK1NXcFFBMzZOc3d1VXRlZ3pONFJwa1V3Z0N3a0t4V0tVUjZ1aW4xCllPcTVGMzhqbXlObGNHUXFpTTR5ZktvdGhBM1Z2VUxRS1JpSlA3T0lGMFlseGcxNG5zQ1hWajZDQ1k5S25HZEYKcWlYY29jakVRVzc2YXo4VXNla0xoN0lGMDk3dHQzZ3R6OU1McExwY3hCMk5YMzRhcW9qVjJlYUY3S3h5MEl2NAp4QWhlSmNndDNudzRHY1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000   # minimum - 600sec/10min
  usages:
  - client auth
