# Exercise 31-02 v3.2.0
#
---
apiVersion: v1
kind: Pod 
metadata:
  name: app01-pod 
  namespace: db-ns 
  labels:
    tier: frontend
spec:
  containers:
    - name: frontend 
      image: nicolaka/netshoot:latest
      ports:
        - containerPort: 3000
        # The command to keep the container running and start the netcat listener.
        # This uses 'nc -l -p 3000 -k' to listen on port 3000 and keep listening after a connection is closed.
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "Starting netcat listener on port 3000..."
          nc -l -p 3000 -k -v &
          # Keep the container running indefinitely
          while true; do
            sleep 3600
          done

---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: db-ns
  labels:
    tier: frontend
spec:
  type: ClusterIP 
  selector:
    pod: app01-pod
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000
