# Exercise 16-02 v3.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web01-pod
  namespace: default
spec:
  containers:
  - name: mem-stress
    image: polinux/stress
    imagePullPolicy: Always
    command:
    - stress
    args:
    - --vm
    - "1"
    - --vm-bytes
    - 250M
    - --vm-hang
    - "1"
    resources:
      limits:
        memory: 300Mi
      requests:
        memory: 300Mi
