# Exercise 28-05 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deploy
spec:
  selector:
    matchLabels:
      pod: loadbalancer-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: loadbalancer-pod
    spec:
      containers:
      - name: stress-container
        image: polinux/stress
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "2000m"
            memory: "2000Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: loadbalancer-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
