# Exercise: 28-05 v3.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01-deploy 
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: web01-pod 
  template:
    metadata:
      labels:
        pod: web01-pod
    spec:
      containers:
      - name: web-app 
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web01-svc 
  namespace: app-ns
spec:
  type: LoadBalancer
  selector:
    pod: web01-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
